### ISSUE TITLE
Build Our Own Online Judge for Open Course

### ISSUE THREAD

**Issue by wisn** [comtran/proposals#1]
Several online judges such as HackerRank and Kattis has their own service for school. That's cool. However, that would cost us so much money. If we could build our own online judge, at least like how Google Code Jam works, that would be good.

Well, that's hella workload for us and will cost money as well. Just let's this dream here.

**Comment by ceefour** [comment]
It's probably good for long term. But for now, I'd say HackerRank works.

For second stage [Submitty](http://submitty.org) can be used. As a plus, students can contribute to it and get a headstart for Google Summer of Code.

In third stage we can actively maintain Submitty with additional support/funding/whatever. I'd prefer joining forces with other open source project(s) then entirely creating our own silo.

The fourth stage we can integrate different technologies and support beyond competitive programming but to academic teaching as well. For example, TelU is already using Moodle (a Google Summer of Code organization!) [for e-elearning](http://elearning.telkomuniversity.ac.id/lms/) that is going to be heavily pushed for lecturers & courses going forward. A mastery of Submitty, Moodle, and coala (all GSoC orgs!) (it's possible to make them work together in a way) for both students & lecturers will be great improvement for CP, academic, and open source activities in TelU.

**Comment by wisn** [comment]
Submitty seems cool and it is what we need. Gonna learn it more later.

Cool beans. Noted.

**Comment by ceefour** [comment]
BTW, there is a good incentive in using/mastering/contributing to Submitty, Moodle, and coala (any of, or combination). HackerRank is already cool, but it's not even yet widely used in TelU academic activities.

Moodle is really old, and it's not yet used extensively in TelU, much less best practices.

However there is progress. Reviewing students' work is one of painpoints of a lecturer, and these tools can help optimize lecturers' time and effort, which also benefits students (better/modern assignments, faster grades release, etc.) Tools like coala also help students improve their coding, which improve their grades, which makes lecturers and the campus happy. So there is a potential benefit here.

While it's hard to imagine lecturers contributing to Submitty, Moodle, and coala; it's actually _very desirable_ to have **students contributing to these projects**. When/if TelU uses them (other than Moodle, which is already here), TelU gets benefits and _incentivizes_ TelU to _fund_ projects which improves these projects or fix bugs. Who better to fund than their own students? (it's a utopian [positive reinforcement cycle](https://en.wikipedia.org/wiki/Positive_feedback), I know, but hey you can dream so I can too..) ;-)

**Comment by ceefour** [comment]
Haha just found this: http://git-awards.com/users?utf8=%E2%9C%93&type=city&language=haskell&city=Bandung congrats @wisn ^_^

**Comment by wisn** [comment]
Hahaha gotta be the first ASAP.

I planned to handle Submitty after finishing my GSoC project. Maybe anyone in @comtran/salesman-nerd could handle this.

**Comment by ceefour** [comment]
Good plan :)

In the meantime, even hackerrank is not yet used in TelU academics (or has it?). So getting this adopted will be a start ...

**Comment by wisn** [comment]
In several courses such as Database Modeling and Database System, HackerRank used as a practice place.

**Comment by ceefour** [comment]
That's awesome! :) I wonder how is it possible to use with these courses, no SQL right ?

**Comment by wisn** [comment]
Yeah, there  is no SQL 🤣
