### ISSUE TITLE
Shared Google Calendar

### ISSUE THREAD

**Issue by ceefour** [comtran/proposals#7]
* [x] Create Google Calendar with all planned COMTRAN activities and upcoming competitions
* [x] Share it with me and COMTRAN members
* [x] Embed on www.comtran.club website

Samples:
* Kubernetes community meeting calendar - https://calendar.google.com/calendar/embed?src=cgnt364vd8s86hr2phapfjc6uk%40group.calendar.google.com&ctz=America/Los_Angeles
* Google Summer of Code: https://calendar.google.com/calendar/hosted/google.com/embed?src=gsummerofcode@gmail.com&ctz=America/Los_Angeles

**Comment by ceefour** [comment]
@comtran/salesman-nerd Please add more events to the calendar, to get write-access invite ask @wisn or me with your gmail

On web: https://www.comtran.club/events.html

**Comment by wisn** [comment]
Thanks, Pak @ceefour! I got quite busy with my GSoC now. I hope @comtran/salesman-nerd could help you.

**Comment by blinfoldking** [comment]
@ceefour i'll see what i can do

**Comment by blinfoldking** [comment]
https://schematics.its.ac.id , a competition from ITS, but it doesn't have any fixed date yet but seems like it's coming really soon, gotta keep an eye on it

**Comment by ceefour** [comment]
@BlinfoldKing Thanks! Just so we remember, I added tentative dates of Schematics NPC to the calendar. Feel free to update them if we have real dates.

**Comment by ceefour** [comment]
![image](https://user-images.githubusercontent.com/24123/40671338-cc4216a2-6395-11e8-9f84-aeb9672f07c2.png)

Based on that, I guess we better get prepared (or at least registered) for COMPFEST X CPC, ACM ICPC Maranatha, and the upcoming Schematics NPC ... oh yeah 😎
